### ISSUE TITLE
Automate Release from Azure

### ISSUE THREAD

**Issue by bollwyvl** [robots-from-jupyter/robotlab#16]
Looks pretty straightforward:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=vsts

Probably just do it on tags, need to find some good examples.

**Comment by bollwyvl** [comment]
Looks like the draft actually got posted! Will check it out this evening!

**Comment by datakurre** [comment]
Cool! I'm just trying those out.

**Comment by bollwyvl** [comment]
If the files showed up at all, that's great! From the log, it looks like
it's pretty chatty... Hopefully there's some way to clean that up.

Anyhooo... I'll re-pr that weird branch I'm working on, get the license
stuff in (one liner), and we should be ready to go.

I'd also like to clear out all those tags I made :p

**Comment by datakurre** [comment]
Minor issue with MacOS. At first I got a selenium related error (Firefox process exited immediately or something; RobotLab was running on my default Firefox). Then, by manually starting Firefox from the cmdline from  ~/robotlab/bin/firefox it started working normally. 

I would guess something with MacOS sandboxing. Cannot be a blocker.

**Comment by datakurre** [comment]
Windows and Linux installers looked good.

**Comment by bollwyvl** [comment]
Thanks for checking those, especially osx!

I've toyed with the idea of getting an osx machine for this purpose, lol.

**Comment by datakurre** [comment]
Thank you for doing all this hard work for the installers :)

**Comment by datakurre** [comment]
Directly from Windows-installation: https://www.youtube.com/watch?v=zcrJirDX28I

**Comment by bollwyvl** [comment]
🤤

**Comment by datakurre** [comment]
https://pypi.org/project/robotframework-seleniumlibrary/ :see_no_evil:

**Comment by datakurre** [comment]
Well, let's get this out at first. It is always possible that major version in seleniumlibrary breaks something in robotkernel's selenium support.

**Comment by datakurre** [comment]
I prepared a blog post https://datakurre.pandala.org/2019/09/introducing-robotlab.html/

**Comment by bollwyvl** [comment]
Yep as soon as the `master` build goes through, we can tag, draft, test and then release.

**Comment by bollwyvl** [comment]
Windows from `v2019.09.0` looks good, trying linux.

**Comment by bollwyvl** [comment]
Linux is also great. Man, I love that simmer selector. :fire: 

AND JUST TO BE SURE, if you can take a crack at that OSX one, I think we can close this out. 

Maybe I'll take a look at getting `JupyterLibrary` back up to speed with SL4 so I know what to expect on #46.

**Comment by datakurre** [comment]
Ok. Trying OSX now...

**Comment by datakurre** [comment]
OSX ok. I tried it on clean user and the experience was great. It launched on Safari by default, but firefox in tests still worked great. 🛫

**Comment by datakurre** [comment]
🚀🎉

**Comment by bollwyvl** [comment]
Closed by https://github.com/robots-from-jupyter/robotlab/releases/tag/v2019.9.0

**Comment by bollwyvl** [comment]
Hooray! If I get a chance, I'll work on tuning up the readme...

**Comment by datakurre** [comment]
Thanks again! Now even I should be able to make releases as long as the pipeline works :)

**Comment by bollwyvl** [comment]
We could set up a nightly job to see if it stays working... But it's one of
those things where: if it fails, so what? If we're not trying to get a
release out, it doesn't really matter, and I'm not looking for more things
to get notified about and fight 🦑🐋

**Comment by datakurre** [comment]
Agreed.
