### ISSUE TITLE
Some shortcuts don't work

### ISSUE THREAD

**Issue by bollwyvl** [robots-from-jupyter/robotlab#17]
Linux looks fine, but the win installer's shortcut doesn't, as I use relative imports on `launch`, which doesn't work the way it is invoked. Working on a fix!

**Comment by datakurre** [comment]
I probably saw that relative import issue also on OSX.

**Comment by bollwyvl** [comment]
Cheers. Don't know how it worked locally!

Ever tested actually clicking on a desktop icon with RF?

**Comment by bollwyvl** [comment]
you could manually apply 7aac3a3 to see if it helps

**Comment by bollwyvl** [comment]
but it does bounce in the dock for a sec?

**Comment by datakurre** [comment]
I confirm this fixed this issue also on OSX.

**Comment by datakurre** [comment]
@bollwyvl Once it worked on OSX the user experience was:

* doc icon appears and disappears immediately after the first bump
* console window opens and starts jupyterlab
* jupterlab is opened on browser
* only console / terminal icon is left on dock

**Comment by bollwyvl** [comment]
Seems fine to me... You want that terminal to be able to kill it off. I
think we'd need wx to do a better job... And then RF Screenshots would
work. But probably not for Wednesday, unless you think the ux is currently
unacceptable!

**Comment by datakurre** [comment]
I'm ok with the ux for Wednesday!
