### ISSUE TITLE
Add robotframeworklexer

### ISSUE THREAD

**Issue by datakurre** [robots-from-jupyter/robotlab#19]
The robot framework lexer currently in Pygments does not support ``*** Tasks ***``.

https://pypi.org/project/robotframeworklexer/ has been updated, but obviously is not yet merged or in downstream in pygments.

Probably adding robotframeworklexer == 1.1 into robotlab would be enough and HTML files exported from robotlab would then highlight tasks properly.

**Comment by bollwyvl** [comment]
I'm on it.

**Comment by bollwyvl** [comment]
closed by #18
