### ISSUE TITLE
Selenium (keywords) not working

### ISSUE THREAD

**Issue by tiiarautavesi** [robots-from-jupyter/robotlab#26]
Hello, I just installed Robotlab to my computer and everything else is working very well, except for some reason I can't use Selenium keywords. Do you have any idea what might cause this? 

![selenium-not-working](https://user-images.githubusercontent.com/17403349/52057075-c39c3200-256c-11e9-9362-a04c40ab54a3.png)

**Comment by tiiarautavesi** [comment]
For some reason it started to work now. Sorry for making this issue case for nothing :robot:

**Comment by tiiarautavesi** [comment]
For some reason it started to work now. Sorry for making this issue case for nothing :robot:

**Comment by bollwyvl** [comment]
Thanks for trying it out... Let's keep this open in case it shows back
up... If so, getting the logs from the terminal window might help! Robot
eats some of the errors in strange ways!

>

**Comment by tiiarautavesi** [comment]
I faced the issue again and realised that the settings cell has to be run first before the selenium key words can work!

**Comment by bollwyvl** [comment]
Ah yes, that will do it!
