### ISSUE TITLE
Release 1.0rc1

### ISSUE THREAD

**Issue by datakurre** [robots-from-jupyter/robotlab#34]
The latest pull did merge as green, so we are ready to tag and release 1.0rc1. I guess, I could still do this one manually.

I’ve done small refresh for https://robots-from-jupyter.github.io/ also.

**Comment by bollwyvl** [comment]
I didn't get the process automated yet. What do we want to do about chrome
driver? I think that's my only sticking point.



Also, as no doubt you've noticed, my response time is pretty poor right now
for various reasons... Is the 1.0 release something we are actually going
to stand behind? Do we need more docs? since this is nominally a 1.0...

**Comment by datakurre** [comment]
@bollwyvl No hurry with this. I can release 1.0rc1 manually. My main motivation go get 1.0 out is to enable semantic versioning. Probably some documentation is required to turn 1.0rc1 into 1.0 final.

Would it be enough to fix chromedriver issue with documentation? It looked like conda-forge includes all versions, and we should have "how to install and upgrade RobotLab packages" documentation anyway?

Once I got widgets support for robotkernel, I realised, that I'm quite happy with its current feature set. Of course, everything could be enhanced forever. I still don't have as good keyword documentation and library/keyword autocompletion as ipythonrobotframwork, I'm still using wrong nbimport library and eventually, the kernel should be rewritten to execute robot step by step instead of executing complete suites...

**Comment by datakurre** [comment]
@esteele Please, try this https://dev.azure.com/robots-from-jupyter/1e5f1f30-0c52-4d28-8cf7-8c72252fbb49/_apis/build/builds/112/artifacts?artifactName=RobotLab%20for%20MacOSX&api-version=5.1-preview.5&%24format=zip

It downloads as a zip and unpacks as a sh. Executing sh-version from terminal does a standalone Miniconda-based installation of Jupyter + RobotFramework tools into a single directory + shortcut on your desktop. Uninstallation is removing those. (Well running it does create some Jupyter configuration directories in "usual locations").

**Comment by datakurre** [comment]
@esteele Then https://robots-from-jupyter.github.io/robotkernel/notebooks/05%20Interactive%20Selenium.html

**Comment by datakurre** [comment]
Superseded by https://github.com/robots-from-jupyter/robotlab/issues/40
