### ISSUE TITLE
Rethink release strategy with robotkernel 1.0

### ISSUE THREAD

**Issue by bollwyvl** [robots-from-jupyter/robotlab#40]
Congratulations on the `robotkernel 1.0` release @datakurre! :raised_hands: 

To coincide with that, we should get a new build out of RobotLab: sorry I haven't been more help on the previous attempts this summer! But it's back to :school: now, let's build some Labs!

# upstreams
- `jupyterlab` 1.1.3 is shaking out to be a pretty solid release after some hiccups up front... there will be no support for the `0.35` line to come, and `1.0.x` might not get much more love, either.
- `restinstance 1.0.2` is out, and not a pre-release, so could probably go ahead and start `conda-forge`ing it
  - same with `robotkernel`, if you'd like

# build chain
- `constructor` can do `noarch` packages now (and got rid of the `bzip` dependency, which has _actually_ caused me troubles)
  - we can shed a lot of recipes in the first place
  - we can build some of the remaining ones just on linux, and reuse them on osx/windows
- `conda run` is back in conda 4.7, which makes the headache of getting `$PATH` (or more specifically, `%PATH%` #39) right less horrible
  - need to investigate what this means for `pyshortcuts`, or if we can get rid of them altogether
- all the azure hosted instances just comes with conda now, so it will be less tedious to get set up

# `xyz`driver
- still a mess :face_with_head_bandage: 
- `geckodriver` 1.0 is probably the next release, and will probably _still_ work for a few years' worth of browsers
- chromedriver.... bah... maybe we just tell people to use firefox :P

# version
I would hesitate to call _any_ RobotLab build a `1.0`, so i propose adopting a different versioning scheme for RobotLab, e.g. `2019.9.0`... if we put out more than one in a month, hooray, but otherwise not so much trouble. 

will do some more thinking (and then some actual doing)...

**Comment by datakurre** [comment]
Thanks. And thanks coming back. I still have not set up proper development environment for RobotLab... :see_no_evil: 

I still try to not think 1.0 as "final", but as something that has been working for me and need to be in proper semver to be able to develop.

Your plans sound good as always. Let's change RobotLab versioning to be date based as proposed and drop shipping (and testing) Chromedriver. Also sounds good that pipeline could be simplified a bit. I was surprised that it fell apart so fast last time (with also other than Selenium testing issues).

RESTinstance 1.0.2 has a small new surprise of re-registering robot-script from robotframework, but that was probably only problem for Nix (conflicting path). Similar issue with Python package `json5`, which has packaged its tests directory into release as global module...

**Comment by bollwyvl** [comment]
> And thanks coming back.

never left, just have been doing lots of day job building, not so much fun stuff! 

> I still try to not think 1.0 as "final",

yeah, but it's still a thing... if you've thought hard enough about how you are willing to break things, that represents some maturity in the code base 

> RobotLab versioning to be date based

yeah, it looks kinda nice, and due to browsery things, is probably a better statement about what each release might mean.

> drop shipping (and testing) Chromedriver.

went ahead with that (new chromedriver dropped literally while i was working on this). bleah. in other news, i've gone ahead and actually shipped firefox, as CF is now [packing 68](https://anaconda.org/conda-forge/firefox/files) (en-US) so you at least have _something_ we know works

> pipeline could be simplified a bit

:surfing_woman: it's looking good, but current run stalled out... kinda too tired to dig into it more now...

>  small new surprise

haha, found that too. PR raised and accepted :tada: 

> packaged its tests directory 

oof. yeah. been there. MANIFEST.in is gross.

apropos of nothing: some shiny things that have been catching my eye:
- [jupyterlab-lsp](https://github.com/krassowski/jupyterlab-lsp)
  - maybe with some surgery, we could be packing both our kernel based stuff as well as [the rf language server](https://github.com/tomi/vscode-rf-language-server)... 
- [jupyterlab-richtext-mode](https://github.com/jupytercalpoly/jupyterlab-richtext-mode)
  - aside from being :fire:, it shows the beginning of the pattern for replacing cell inputs, which could be combined with...
- the phosphor data grid that should be in the next lab minor (1.2) supports a full excel-style selection model
  - overlay an itty bitty codemirror, and we could have a RIDE-like grid, backed by a kernel with all the completion stuff. yum. 
  - slap a little bit of tree control on it, and we can do a nice in-lab browser for test reports

**Comment by datakurre** [comment]
Do I understand correctly that the lsp server and its lab integration would handle all usual auto completion and similar IDE features and RF kernels could focus on the fancy stuff like proper step by step code execution? Btw, is there already UI extension available for stepping code lines within a cell?

**Comment by bollwyvl** [comment]
> handle all usual auto completion and similar IDE features

Yeah, but as it's written in node it can't easily follow more exotic imports... e.g it ships pre-canned robot standard library completions and you have to do _stuff_ to make it handle your libs. It's more the go to definition, find symbol and other fun things.

>  stepping code lines within a cell 

it's on-going... https://github.com/jupyterlab/debugger

**Comment by bollwyvl** [comment]
Closed by https://github.com/robots-from-jupyter/robotlab/releases/tag/v2019.9.0
