### ISSUE TITLE
Validate against SeleniumLibrary 4

### ISSUE THREAD

**Issue by bollwyvl** [robots-from-jupyter/robotlab#46]
We'll need to pin to `<4` to get the release out.

**Comment by datakurre** [comment]
I cannot find any issues with SeleniumLibrary 4.0.0. I will make a pull for it.

**Comment by datakurre** [comment]
https://github.com/robots-from-jupyter/robotlab/pull/50

**Comment by datakurre** [comment]
The new behavior of `Open Browser alias=something` is very cool. It no longer opens new browser windows if one with that alias is already open. Working perfectly with robotkernel sticky selenium sessions.

**Comment by bollwyvl** [comment]
Ooooh! Thanks for trying it out! Sounds all ergonomic and stuff.

This raises the question of when we would want to drop the next release...
Wait until 2019.10? Continuous delivery is fun and all...

**Comment by bollwyvl** [comment]
Closed by #50

**Comment by datakurre** [comment]
How much fun it really is? 🙃I push a tag and the robot drafts the release? If everything is automated up to draft and even I could make that, then I could practise 2019.09.1

**Comment by bollwyvl** [comment]
Right it's great for us, but not so for users if we push a bad
installer. CD should
have some way of knowing if the deploy is broken, and then rolling back. Users
will find/bring problems we can't even imagine, and it can be very hard to
get a useful error report... It's more likely people just leave.

I guess we could initially mark them as pre-release (doesn't get shown by
default)...

**Comment by datakurre** [comment]
But isn’t it draft until we promote it?

And it yes, what I actually should do? Push a tag?

**Comment by bollwyvl** [comment]
Yes, we do have that manual step in place... So it's not quite CD. Maybe
OCD.

If we want to go for it, we'd make a PR:
- bump everything back down to 2019.9.1 (three places I think)
  - I was being conservative with the 10 version
  - update the changelog,
- build/test/merge the pr
- tag/build/test/draft
  - either with push --tags or through the web ui
- manually test the built installers
- fix the release notes
- publish!

Getting there! I should make an issue for generating the release notes...
It would be nice to have at least the updated/new package tables made from
ground truth (what actually got installed). Heck, I'd like to have links to
_those_ changelogs, but that's not in the metadata at present (sadly).

We could also consider something like rever:
https://github.com/regro/rever
But it has many opinions.

**Comment by datakurre** [comment]
Thanks for the details. 2019.10.0 fits for me :) I’ll try out those steps next week.

**Comment by bollwyvl** [comment]
Yeah we should probably split out a CONTRIBUTING.md, and formalize the
process.
