### ISSUE TITLE
As newcomer I did expect robot file to open as a new notebook 

### ISSUE THREAD

**Issue by datakurre** [robots-from-jupyter/robotlab#49]
Is there a hook in Jupyter that would allow us to import a raw source file?

Sure a good experience would not be trivial, because we should split the source into cells in some sane way. It could require parsing and generating the file.

**Comment by datakurre** [comment]
The easiest workaround is to copy paste entire file into a single cell and learn cell splitting keyword to split it into practical chunks.

**Comment by bollwyvl** [comment]
heh. well, i have been avoiding doing new _code_ work specifically for RobotLab, but...

- frontend
  - We can add a right-click menu item on `.robot` and `.resource` files, e.g. `Open as Notebook`, and do all the plumbing for splitting, etc. in-browser. Of course, it would end up being _another_ parser, though we _might_ be able to re-purpose some of the stuff from the syntax highlighter.
- backend
  - somehow work with nbconvert 
  - somehow work with [jupytext](https://github.com/mwouts/jupytext)

Also, apropos of nothing, I might rep RobotLab at the [community call](https://discourse.jupyter.org/t/jupyter-community-calls/668) tomorrow. Folks would be familiar with Jupyter stuff, but less so with Robot. Part of it would just be "Hey, you can distribute complex Jupyter-y things that aren't _just_ python".

**Comment by datakurre** [comment]
I would expect that there has been similar ideas for imports Python source files 🤔

I agree on that we really should not hurry on cluttering the interface with. we buttons.

**Comment by datakurre** [comment]
I should look into getting robot support into jupytext. That’s definitely higher priority.

**Comment by datakurre** [comment]
Jupytext should do this now in RobotLab 2019.12.0. Although, the resulting notebooks needs joining of cells to make the notebook usable. But that would be an issue for jupytext (for us) to provide better robot => notebook conversion.
