### ISSUE TITLE
Feature request: Support for visual studio code (or other ide)

### ISSUE THREAD

**Issue by anton264** [robots-from-jupyter/robotlab#55]
It would be convinient to be able to use robotlab in an IDE.
Visual studio has support for jupyter but i cant find a way to make it understand robot syntax.

**Comment by datakurre** [comment]
PyCharm has the same, the last time I tried it was very tied only support Python kernels. I assume that Visual Studio is the same, but we’ll be following this.

In theory, when IDEs have full IPython kernel support, robotkernel or ipythonrobotframework should just work.

**Comment by bollwyvl** [comment]
Yeah, wearing my jupyter hat, there is a good amount of collaboration by our community with the vscode (and other communities) in getting more Jupyter protocols and components supported by more tools. But we're mostly volunteers, and are focused on delivering value across an extremely wide swathe of users and downstreams, many of which for whom a web-delivered, permissively licensed, flexibly-deployed, extensible, client/server without built-in telemetry is very important.

We're busy working the other way, too, integrating vscode-lead open protocols into jupyter(lab): e.g. the [language server protocol](https://github.com/krassowski/jupyterlab-lsp) and the [debug adapter protocol](https://github.com/jupyterlab/debugger). 

Putting my robots-from-jupyter hat back on, we're exactly two volunteer maintainers (PRs welcome!) and a small community of brave users (:heart:): as @datakurre suggests, if community X just supports one Jupyter experience vertical (e.g. local, IPython- _like_, reimplemented with another protocol) there's little hope that irobotframework or robotkernel are going to be made to work, and more importantly, supported, whereas if X implements the full stack (from kernelspecs to the kernel message protocol to widgets) then everything should _Just Work :tm:_. We're probably not going to be able support development on integrating with X, as there's a high chance we're not daily users of tool X, and would not be able to confidently extend our workshop material content to support X, Y, Z... much less support requests for _those_ tools when they break on Windows OSX Arch Home Pro Office Server 7-2019-Catalina-Snow Leopard.

Another tack to take for _this_ X would be to check out [vscode-rf-language-server](https://github.com/tomi/vscode-rf-language-server) or [robotframework-rflsp](https://github.com/rasjani/robotframework-rflsp) or [robotframework-debug](https://marketplace.visualstudio.com/items?itemName=JacobPhilip.danfoss-robotframework-debug&ssr=false#overview) and see if you can request (or contribute!) features from (i)robot(kernel|framework)! All of our stuff is permissively licensed, and available on github (at least) or pip/npm.

**Comment by datakurre** [comment]
Just checked that PyCharm still only supports Python notebooks. Executing robot notebooks (with externally running Jupyter server) displays error "Can not execute non-Python notebook cells (notebook language is robotframework)."

That said, I'm quite optimistic that this will happen. We are not able to implement or support IDE-integrations, but by following IPython kernel protocols our Robot Framework Jupyter kernels are ready when IDEs start supporting Jupyter in more generic manner.

**Comment by datakurre** [comment]
VSCode seems to still be one iteration behind from PyCharm. It expects all notebooks to be Python notebooks.

**Comment by datakurre** [comment]
VSCode is working on supporting other kernels, but having language specific IDE features for minor languages like Robot Framework might take time: https://github.com/microsoft/vscode-python/issues/5078

**Comment by bollwyvl** [comment]
Yeah it's really a shame the vscode community didn't go through the JEP
process to get this added to the kernel message spec in a way that would
benefit all kernel users (and writers!), with a reference implementation in
IPython. Pycharm isn't open source, so I wouldn't expect it, but would be
happy to be pleasantly surprised.

**Comment by datakurre** [comment]
@anton264 FYI. I added robot support for jupytext Jupyter extension https://github.com/datakurre/jupytext (and submitted pull for that to upstream).

**Comment by datakurre** [comment]
https://github.com/robots-from-jupyter/robotlab/releases/tag/v2019.12.0 ships with jupytext that can convert Robot notebooks to Robot files for editing and synchronizes changes back. That's the best we can do right now.

![jupytext-robot](https://user-images.githubusercontent.com/160447/70512115-6bdd3880-1b38-11ea-8560-0d08dabebf40.gif)

https://readthedocs.org/projects/jupytext/
