### ISSUE TITLE
RobotLab 2019.12.0

### ISSUE THREAD

**Issue by datakurre** [robots-from-jupyter/robotlab#57]
Updates

* [x] robotframework-seleniumlibrary 4.1.0
* [x] robotkernel 1.1 (unreleased)

Additions

* [x] robotframework-seleniumtestability > 0.0.15 (unreleased, a lot of changes in master since 0.0.15)
* [x] jupytext 1.3.0 (supports Robot Framework)

What else?

**Comment by datakurre** [comment]
I fell into rabbit hole in upgrading robotkernel for Robot Framework 3.2. I try to finish it this week so that we could try release in early December, probably still with the latest Robot Framework 3.1.x, but sure if it would be great, if it could be upgrade to robotframework 3.2 with pip.

**Comment by bollwyvl** [comment]
Watch out for the 🐰 with big point teeth! I'll take a look in a couple
hours! Probably need to revise the syntax highlighting for IF🕺🏽

**Comment by bollwyvl** [comment]
looking at it now...

**Comment by bollwyvl** [comment]
ok, this is an issue, not a PR... do you have any code yet? i'll start updating the things that are already released on pypi, even if pre-release, will hang back on things that are still in-flight.

**Comment by datakurre** [comment]
@bollwyvl No code yet. I'll ping you once there's something to see. I got side tracked...

**Comment by datakurre** [comment]
Closing this in favor of new pull requests.
